CREATE TABLE IF NOT EXISTS history (
  id INT NOT NULL AUTO_INCREMENT,
  expression VARCHAR(255) NOT NULL,
  result VARCHAR(255) NOT NULL,
  title VARCHAR(255) NULL,
  created_at VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;